#! /usr/bin/env python
# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES.
#                         All rights reserved.
# SPDX-License-Identifier: Apache-2.0

import argparse
import glob
import json
import os
import site
import subprocess as sp
from contextlib import contextmanager
from email.parser import Parser
from pathlib import Path

import requests


@contextmanager
def in_folder(f):
    topdir = os.getcwd()
    os.chdir(f)
    try:
        yield
    finally:
        os.chdir(topdir)


def get_record(pkg):
    cmd = ["pip", "show", "--files", pkg]
    output = sp.check_output(cmd).decode("utf-8")
    header = Parser().parsestr(output)
    if header["Location"] is not None:
        root = Path(header["Location"])
        files = [f.strip() for f in header["Files"].strip().splitlines()]
        for f in files:
            path = root / f
            if path.name == "RECORD":
                return path

    for sitedir in site.getsitepackages():
        with in_folder(sitedir):
            folders = glob.glob(f"{pkg}*dist-info*")
            for folder in folders:
                record = Path(folder) / "RECORD"
                if record.exists():
                    return record.resolve()

    raise Exception(f"No RECORD found for {pkg}")


def fetch_needed(pkg):
    record = get_record(pkg)
    if record is not None:
        installed = open(record).read().strip().splitlines()
        for i in installed:
            obj = i.split(",")[0]
            if ".so" in obj:
                return True

    return False


def clean_giturl(url):
    # there may be other garbage included
    print(url)
    http, _, github_com, org, repo = url.split("/")[:5]
    return f"https://github.com/{org}/{repo}"


def get_giturl(info):
    for name in "home_page", "download_url":
        if name in info:
            url = info[name]
            if url and "//github.com" in url:
                return clean_giturl(url)

    if "project_urls" in info:
        urls = info["project_urls"]
        if urls is not None:
            for key, value in urls.items():
                if "github" in value:
                    return clean_giturl(value)

    return None


def download_tarball(tar_url, folder):
    response = requests.get(tar_url, stream=True)
    tarball = Path(tar_url).name
    if response.status_code == 200:
        print(f"saving {tar_url} locally")
        folder.mkdir(parents=True, exist_ok=True)
        with open(folder / tarball, "wb") as f:
            f.write(response.raw.read())
        return True


def download_url(giturl, ref, folder):
    tar_url = giturl + "/archive/" + ref + ".tar.gz"
    download_tarball(tar_url, folder)


def fetch(pkg: str, version: str):
    url = "https://pypi.org/pypi/"
    folder = Path("pip") / pkg
    if folder.exists():
        return

    local_path = Path(pkg + ".json.cached")
    if local_path.exists():
        with open(local_path) as f:
            r = json.load(f)
    else:
        r = requests.get(url + pkg + "/json").json()
        with open(local_path, "w") as f:
            json.dump(r, f, indent=2)

    info = r["info"]
    giturl = get_giturl(info)
    print(f"found {pkg}=={version} at {giturl}")
    cmd = ["git", "ls-remote", "--tags", giturl]
    output = sp.check_output(cmd).decode("utf-8")

    releases = []
    for line in output.strip().splitlines():
        if "{}" not in line:
            ref = line.split()[-1].strip()
            releases.append(ref)
            if version in ref:
                download_url(giturl, ref, folder)
                return True

    if releases:
        print(f"Failed to find matching release {version}, using most recent")
        download_url(giturl, releases[-1], folder)
        return True
    else:
        print(f"No releases found: {output} {json.dumps(info,indent=2)}")

    return False


parser = argparse.ArgumentParser()
parser.add_argument(
    "--pkgs",
    type=str,
    required=True,
    help="Path to a file containing the output of `pip list installed`",
)
args = parser.parse_args()
pkgs = open(args.pkgs).read().splitlines()

for line in pkgs:
    split = line.split()
    if len(split) == 2:
        try:
            pkg, version = line.split()
            folder = Path("pip") / pkg
            if folder.exists():
                print(pkg, "already fetched")
                continue

            if fetch_needed(pkg):
                print(pkg, "needs fetch")
                fetch(pkg, version)
            else:
                folder.mkdir(parents=True, exist_ok=True)

        except Exception as e:
            print(pkg, "failed", e)

    elif len(split) == 3:
        print("SOURCE: ", split)
