ARG COMMIT_IMAGE
FROM ${COMMIT_IMAGE} AS commit

COPY workspace/jax /opt/workspace/jax
COPY workspace/legate-jax /opt/workspace/legate-jax

COPY entrypoint.sh /opt/entrypoint.sh
ENTRYPOINT [ "/opt/entrypoint.sh" ]
CMD [ "/bin/bash" ]
