ARG CUDA_VERSION
ARG CUDNN_VERSION
FROM nvidia/cuda:${CUDA_VERSION}-cudnn${CUDNN_VERSION}-devel-ubuntu22.04 AS conda_base

SHELL [ "/bin/bash", "-eo", "pipefail", "-c" ]

COPY install-apt.sh /opt
RUN /opt/install-apt.sh

ENV CUDA_PATH="/usr/local/cuda/lib64/stubs"

ARG CUSTOM_NCCL
COPY nccl /opt/nccl
COPY build-nccl.sh /opt/nccl
RUN echo ${CUSTOM_NCCL} && cd /opt/nccl && CUSTOM_NCCL="${CUSTOM_NCCL}" && ./build-nccl.sh

COPY install-bazel.sh /opt
RUN /opt/install-bazel.sh

COPY install-conda.sh /opt
RUN /opt/install-conda.sh

ENV LD_LIBRARY_PATH="/opt/install/miniconda/envs/legere/lib:${LD_LIBRARY_PATH}"
ENV PATH="/opt/install/miniconda/bin:${PATH}"

FROM conda_base AS mellanox_download

RUN cd /opt && \
  curl -fsSL http://content.mellanox.com/ofed/MLNX_OFED-5.4-3.5.8.0/MLNX_OFED_LINUX-5.4-3.5.8.0-ubuntu22.04-x86_64.tgz | tar -xz

FROM conda_base AS mellanox_install
COPY ibdev2netdev /usr/bin
COPY install-mofed.sh /opt
RUN --mount=type=cache,from=mellanox_download,source=/opt/MLNX_OFED_LINUX-5.4-3.5.8.0-ubuntu22.04-x86_64,target=/opt/MLNX_OFED_LINUX-5.4-3.5.8.0-ubuntu22.04-x86_64 \
  /opt/install-mofed.sh

FROM mellanox_install AS ucx_build
COPY download-build-ucx.sh /opt
RUN /opt/download-build-ucx.sh

FROM mellanox_install AS ucx_install
RUN --mount=type=cache,from=ucx_build,source=/opt/ucx,target=/opt/ucx \
  cd /opt/ucx && make -j install

FROM ucx_install AS legion_build
COPY legion /opt/legion
COPY build-legion.sh /opt
RUN /opt/build-legion.sh

FROM ucx_install AS legion_install
RUN --mount=type=cache,from=legion_build,source=/opt/legion,target=/opt/legion \
  cd /opt/legion && \
  conda run --no-capture-out -n legere cmake --install build --prefix \
    /opt/install/miniconda/envs/legere


FROM legion_install AS legate_build
COPY legate /opt/legate
COPY build-legate.sh /opt
RUN /opt/build-legate.sh


FROM legion_install AS legate_install
COPY install-legate.sh /opt
RUN --mount=type=cache,from=legate_build,source=/opt/legate,target=/opt/legate \
  /opt/install-legate.sh

FROM legate_install AS jaxlib_build
ARG BAZEL_CACHE=grpc://host.docker.internal:9092
ENV PATH=$PATH:/opt/bazel
COPY xla /opt/xla
COPY jaxlib /opt/jaxlib
COPY build-jaxlib.sh /opt
RUN /opt/build-jaxlib.sh ${BAZEL_CACHE}



FROM legate_install AS jaxlib_install
RUN --mount=type=cache,from=jaxlib_build,source=/opt/jaxlib,target=/opt/jaxlib \
  cd /opt/jaxlib && conda run --no-capture-out -n legere python -m pip install dist/*.whl


FROM jaxlib_install AS jax_download
COPY jax /opt/jax

FROM jaxlib_install AS jax_install
RUN --mount=type=cache,from=jax_download,source=/opt/jax,target=/opt/jax \
  cd /opt/jax && conda run --no-capture-out -n legere python -m pip install .


FROM jax_install AS legate_jax_build
ARG BAZEL_CACHE=grpc://host.docker.internal.9092
COPY xla /opt/xla
COPY legate-jax /opt/legate-jax
COPY build-legate-jax.sh /opt
RUN /opt/build-legate-jax.sh

FROM jax_install AS legate_jax_install
COPY install-legate-jax.sh /opt
RUN  --mount=type=cache,from=legate_jax_build,source=/opt/legate-jax,target=/opt/legate-jax \
  --mount=type=bind,from=legate_jax_build,source=/opt/xla,target=/opt/xla \
  /opt/install-legate-jax.sh


FROM legate_jax_install AS build_te
COPY te /opt/te

FROM legate_jax_install AS install_te
COPY install-te.sh /opt
RUN conda run -n legere python -m pip install cmake
RUN --mount=type=cache,from=build_te,source=/opt/te,target=/opt/te \
  /opt/install-te.sh

FROM install_te AS download_paxml_repos

COPY chex /opt/chex
COPY flax /opt/flax
COPY clu /opt/clu
COPY optax opt/optax
COPY seqio /opt/seqio
COPY orbax /opt/orbax


FROM install_te AS install_paxml_repos

COPY requirements.txt /opt
COPY install-pip-dependencies.sh /opt
COPY praxis /opt/praxis
COPY paxml /opt/paxml

RUN \
   --mount=type=cache,from=download_paxml_repos,source=/opt/chex,target=/opt/chex \
   --mount=type=cache,from=download_paxml_repos,source=/opt/flax,target=/opt/flax \
   --mount=type=cache,from=download_paxml_repos,source=/opt/clu,target=/opt/clu \
   --mount=type=cache,from=download_paxml_repos,source=/opt/optax,target=/opt/optax \
   --mount=type=cache,from=download_paxml_repos,source=/opt/seqio,target=/opt/seqio \
   --mount=type=cache,from=download_paxml_repos,source=/opt/orbax,target=/opt/orbax \
   /opt/install-pip-dependencies.sh

FROM install_paxml_repos AS paxml_image

COPY tags /opt/tags

COPY entrypoint.sh /opt/entrypoint.sh
COPY legate-jax/examples/paxml/run.py /opt

ENTRYPOINT [ "/opt/entrypoint.sh" ]

CMD [ "/bin/bash" ]
