#! /usr/bin/env bash

set -e

BUILD_TYPE=$1
BUILD_DIR=/opt/build/realm
LIB_DIR=/opt/lib

set -e

pushd /opt/workspace/realm

export CCACHE_DIR=/realm-ccache

conda run --no-capture-out -n legere cmake -S . -B ${BUILD_DIR} -DCMAKE_GENERATOR:STRING=Ninja \
  -DCMAKE_CXX_COMPILER:PATH=/usr/bin/g++ -DCMAKE_C_COMPILER:PATH=/usr/bin/gcc \
  -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
  -DCMAKE_LIBRARY_PATH:STRING=/usr/lib/x86_64-linux-gnu -DCMAKE_CXX_STANDARD:STRING=17 \
  -DBUILD_SHARED_LIBS:BOOL=ON -DCMAKE_BUILD_TYPE:STRING="${BUILD_TYPE}" -DLegion_USE_CUDA:BOOL=ON \
  -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=${LIB_DIR} \
  -DCMAKE_ARCHIVE_OUTPUT_DIRECTORY=${LIB_DIR} \
  -DCMAKE_CUDA_COMPILER_LAUNCHER=ccache \
  -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
  -DCMAKE_C_COMPILER_LAUNCHER=ccache \
  -DCMAKE_CXX_FLAGS_RELWITHDEBINFO="-O2 -ggdb" \
  -DCMAKE_CXX_FLAGS_DEBUG="-O0 -ggdb" \
  -DBUILD_MARCH= \
  -DLegion_CUDA_DYNAMIC_LOAD:BOOL=ON \
  -DLegion_MAX_DIM:STRING=5 -DLegion_USE_OpenMP:BOOL=ON -DLegion_USE_GASNet:BOOL=OFF \
  -DLegion_USE_Python:BOOL=OFF -DLegion_VERSION:STRING=24.9.0 -DLegion_BUILD_BINDINGS:BOOL=OFF \
  -DLegion_REDOP_COMPLEX:BOOL=OFF -DLegion_HIJACK_CUDART:BOOL=OFF -DLegion_GPU_REDUCTIONS:BOOL=OFF \
  -DLegion_REDOP_HALF:BOOL=OFF -DCUDA_NVCC_FLAGS:STRING=-std=c++17 \
  -DLegion_MAX_NUM_NODES=4096 \
  -DLegion_DEFAULT_LOCAL_FIELDS:STRING=0 -DLegion_NETWORKS:STRING=ucx \
  -DCMAKE_INSTALL_RPATH:PATH=/opt/install/miniconda/envs/legere/lib \
  -DCMAKE_INSTALL_PREFIX:PATH=/opt/install/miniconda/envs/legere

ln -s $BUILD_DIR/compile_commands.json

popd
