---
name: Build docker image

concurrency:
  group: ${{ startsWith(github.ref_name, 'main') && format('unique-{0}', github.run_id) || format('ci-build-docker-image-{0}-from-{1}', github.event_name, github.ref_name) }}
  cancel-in-progress: true

on:
  workflow_call:
    inputs:
      stage:
        description: 'The Dockerfile stage to build up to'
        required: true
        default: 'reinstall_custom_jax'
        type: string
      tag:
        description: 'The docker tag to append to the image: name:tag'
        required: true
        default: 'maxtext'
        type: string
      base_image:
        description: 'The base stage/image to build maxtext from'
        default: 'ghcr.io/nv-legate/legate-jax-dev:base'
        type: string

permissions:
  packages: write
  contents: read

jobs:
  build:
    runs-on: linux-amd64-cpu16

    defaults:
      run:
        shell: bash -xeuo pipefail {0}

    steps:
      - name: Echo input settings
        run: |
          echo "Base image = ${{ inputs.base_image }}"
          echo "Stage = ${{ inputs.stage }}"
          echo "Tag = ${{ inputs.tag }}"

      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: true
          ssh-key: ${{ secrets.SSH_KEY_NV_SUBMODULES }}
          fetch-depth: 0

      - name: Stop all Docker containers
        run: |
          # Only try to stop if there are running containers.
          if [ -n "$(docker ps -q)" ]; then
            docker stop $(docker ps -q)
          fi

      - name: Setup environment variables
        run: |
          cd ..
          mkdir -p cache
          cd cache
          echo "CACHE_DIR=$(pwd)" >> $GITHUB_ENV

      - name: Restore cache
        id: cache-build
        uses: actions/cache@v3
        with:
          path: ${{ env.CACHE_DIR }}
          key: legate-jax-workflows

      - name: Start bazel cache
        run: |
          docker run -u 1000:1000 -d -v ${{ env.CACHE_DIR }}:/data \
            -p 9090:8080 -p 9092:9092 buchgr/bazel-remote-cache \
            --max_size 30

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: 3.12
          auto-update-conda: true
          use-mamba: true
          channels: conda-forge,defaults
          activate-environment: LJW

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Generate a development docker image
        run: |
          export CONDA_ENV=LJW

          activate_conda_env() {
              set +xu
              eval "$(conda shell.bash hook)"
              conda activate "${CONDA_ENV}";
              set -xu
          }

          activate_conda_env

          conda info

          ./bootstrap.sh

          cd docker
          ./build.py --no-cache --framework maxtext --base-image ${{ inputs.base_image }} --stage ${{ inputs.stage }}

      - name: Push image to ghcr.io
        run: |
          docker tag "${{ inputs.tag }}" "ghcr.io/nv-legate/legate-jax-workflows/${{ inputs.tag }}"
          docker push "ghcr.io/nv-legate/legate-jax-workflows/${{ inputs.tag }}"

  test:
    needs:
      - build
    runs-on: linux-amd64-2gpu

    container:
      options: --cap-add SYS_ADMIN --entrypoint /opt/entrypoint.sh --gpus 0
      image: ghcr.io/nv-legate/legate-jax-workflows/legate-jax-dev:maxtext
      env:
        NVIDIA_VISIBLE_DEVICES: ${{ env.NVIDIA_VISIBLE_DEVICES }}

    defaults:
      run:
        shell: bash -xeuo pipefail {0}
        working-directory: /opt/workspace/legate-jax

    steps:
      - name: Run Microbatch smoke test
        run: |
          python tests/python/jax_microbatch_test.py --cpus 1

      - name: Run Task unit tests
        run: |
          for n in 2 4 8; do
            python tests/python/jax_auto_task_test.py --cpus $n
          done

      - name: Run Maxtext validation
        run: |
          ./validate-cpu.sh
