---
name: Build docker image

concurrency:
  group: ${{ startsWith(github.ref_name, 'main') && format('unique-{0}', github.run_id) || format('ci-build-docker-image-{0}-from-{1}', github.event_name, github.ref_name) }}
  cancel-in-progress: true

on:
  push:
    branches:
      - "pull-request/[0-9]+"
      - "branch-*"
      - "main"
      - "sandeepd/add_ci"
  merge_group:

jobs:
  build:
    runs-on: linux-amd64-20cpu

    defaults:
      run:
        shell: bash -xeuo pipefail {0}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: true
          ssh-key: ${{ secrets.SSH_KEY_NV_SUBMODULES }}
          fetch-depth: 0

      - name: Bootstrap submodules
        run: |
          ./bootstrap.sh

      # - name: Start Bazel cache
      #   run: |
      #     cd docker
      #     ./start-cache.sh

      - name: Generate a development docker image
        run: |
          export PATH=$PATH:/opt/miniconda3/bin
          export CONDA_ENV=ljw

          activate_conda_env() {
              set +xu
              eval "$(conda shell.bash hook)"
              conda activate "${CONDA_ENV}";
              set -xu
          }

          conda create -n ${CONDA_ENV} -c conda-forge python=3.12 pyyaml subprocess-tee

          activate_conda_env

          cd docker
          ./build.py --no-cache --framework maxtext

          # docker build -t legate-jax-dev:maxtext - <<EOF
          # FROM busybox
          # C_M_D echo "Hello from Busybox"
          # EOF

      - name: Save Docker image to file
        run: |
          cd ..
          mkdir artifacts
          cd artifacts
          echo "ARTIFACTS_DIR=$(pwd)" >> $GITHUB_ENV
          docker save legate-jax-dev:maxtext -o legate-jax-dev-maxtext.tar

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: legate-jax-dev-maxtext
          path: "${{ env.ARTIFACTS_DIR }}/legate-jax-dev-maxtext.tar"
