on:
  push:
    branches:
      - "pull-request/[0-9]+"
      - "branch-*"
      - "main"
      - "sandeepd/*"

jobs:
  build:
    uses: ./.github/workflows/base-workflow.yml
    with:
      tag: maxtext
      base_image: ghcr.io/nv-legate/legate-jax-dev:devcontainer_base
      stage: reinstall_custom_jax
    secrets: inherit
